sudo: false
dist: bionic
language: python
python:
  - "2.7"
  # - "3.6"
  # - "3.7"
  # - "3.8"

cache: pip

addons:
  apt:
    update: true
    packages:
      - python-glade2
      - python-stdeb
      - python-gtk2
      - python-gtk2-dev
      - python-all
      - debhelper

script:
  - pip --version
  # - pip install .
  # - pip install PyGTK
  - python --version
  - python FAHControl
